# Generated by Django 3.0 on 2022-06-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_service', models.CharField(default='', max_length=200)),
                ('first_package', models.PositiveSmallIntegerField(default=0)),
                ('second_package', models.PositiveSmallIntegerField(default=0)),
                ('third_package', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
