# Generated by Django 3.0 on 2023-05-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_flyer', models.PositiveSmallIntegerField(default=0)),
                ('frontend', models.PositiveSmallIntegerField(default=0)),
                ('backend', models.PositiveSmallIntegerField(default=0)),
                ('devops', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='emailCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=50)),
                ('name', models.CharField(default='', max_length=50)),
                ('subscribe', models.BooleanField(default=False)),
                ('sent_message', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='emailFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=100)),
                ('file', models.FileField(blank=True, max_length=1000, upload_to='emailfile/')),
            ],
        ),
        migrations.CreateModel(
            name='PaypalClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_env', models.CharField(default='', max_length=200, unique=True)),
                ('client_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_service', models.CharField(default='', max_length=200)),
                ('first_package', models.PositiveSmallIntegerField(default=0)),
                ('second_package', models.PositiveSmallIntegerField(default=0)),
                ('third_package', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
