# Generated by Django 3.0 on 2022-06-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_env', models.CharField(default='', max_length=200)),
                ('client_id', models.TextField()),
            ],
        ),
    ]
