# Generated by Django 3.0 on 2022-06-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0002_paypalclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalclient',
            name='name_of_env',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
