# Generated by Django 3.0 on 2022-07-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0003_auto_20220613_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=500)),
                ('email', models.TextField(default='')),
                ('name', models.CharField(default='', max_length=200)),
                ('subscribe', models.BooleanField(default=False)),
                ('sent_message', models.BooleanField(default=False)),
            ],
        ),
    ]
