# Generated by Django 3.0 on 2022-07-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0004_emailcampaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='emailcampaign',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
