# Generated by Django 3.0 on 2022-07-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0005_auto_20220707_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='customPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_flyer', models.PositiveSmallIntegerField(default=0)),
                ('frontend', models.PositiveSmallIntegerField(default=0)),
                ('backend', models.PositiveSmallIntegerField(default=0)),
                ('web_design', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
