# Generated by Django 3.0 on 2022-07-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0006_customprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customprice',
            old_name='web_design',
            new_name='devops',
        ),
    ]
