# Generated by Django 3.0 on 2022-08-02 19:02

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital', '0007_auto_20220710_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.PositiveSmallIntegerField(default=0)),
                ('file', models.FileField(blank=True, max_length=1000, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='emailfile/')),
            ],
        ),
    ]
